<?php

namespace App\Repository;
use App\Entity\Consultations;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use \Doctrine\ORM\QueryBuilder;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\Persistence\ObjectRepository;
use Doctrine\Persistence\ManagerRegistry;
/**
 * PatientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationsRepository extends ServiceEntityRepository{
	 protected $objectManager;
    
    public function __construct(ManagerRegistry $registry ) {
        parent::__construct($registry, Consultations::class);
        // $this->objectManager = $om;
    }
     /**
     * @return ObjectRepository
     */
    protected function getRepository()
    {
        return $this->objectManager->getRepository($this);
    }

    public function findMedecin($id){ 
        $qb = $this->createQueryBuilder('u')->select("u");
        $qb->where("u.medecin like :room")->setParameter("room", '%'.$id.'%');
         
        return $qb->getQuery()->getResult();
    }
}
